<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2H8M6H2" failures="2" tests="2" name="Test" time="68.403" errors="0" timestamp="2023-02-28T21:44:39 IST">
  <testcase classname="tests.FourTest" name="testfour" time="67.576">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.FourTest.testfour(FourTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testfour -->
  <testcase classname="tests.FourTest" name="testfour" time="67.926">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at resources.Base.takescreenshot(Base.java:38)
at listners.Listners.onTestFailure(Listners.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testfour -->
</testsuite> <!-- Test -->
